// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "time"

// AlertHistoryState undocumented
type AlertHistoryState struct {
	// AppID undocumented
	AppID *string `json:"appId,omitempty"`
	// AssignedTo undocumented
	AssignedTo *string `json:"assignedTo,omitempty"`
	// Comments undocumented
	Comments []string `json:"comments,omitempty"`
	// Feedback undocumented
	Feedback *AlertFeedback `json:"feedback,omitempty"`
	// Status undocumented
	Status *AlertStatus `json:"status,omitempty"`
	// UpdatedDateTime undocumented
	UpdatedDateTime *time.Time `json:"updatedDateTime,omitempty"`
	// User undocumented
	User *string `json:"user,omitempty"`
}
