// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DefaultColumnValue undocumented
type DefaultColumnValue struct {
	// Formula undocumented
	Formula *string `json:"formula,omitempty"`
	// Value undocumented
	Value *string `json:"value,omitempty"`
}
