// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DriveItemVersionRequestBuilder is request builder for DriveItemVersion
type DriveItemVersionRequestBuilder struct{ BaseRequestBuilder }

// Request returns DriveItemVersionRequest
func (b *DriveItemVersionRequestBuilder) Request() *DriveItemVersionRequest {
	return &DriveItemVersionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// DriveItemVersionRequest is request for DriveItemVersion
type DriveItemVersionRequest struct{ BaseRequest }

// Get performs GET request for DriveItemVersion
func (r *DriveItemVersionRequest) Get() (resObj *DriveItemVersion, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest("GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for DriveItemVersion
func (r *DriveItemVersionRequest) Update(reqObj *DriveItemVersion) error {
	return r.JSONRequest("PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for DriveItemVersion
func (r *DriveItemVersionRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
