// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// VPPTokenAccountType undocumented
type VPPTokenAccountType string

const (
	// VPPTokenAccountTypeVBusiness undocumented
	VPPTokenAccountTypeVBusiness VPPTokenAccountType = "business"
	// VPPTokenAccountTypeVEducation undocumented
	VPPTokenAccountTypeVEducation VPPTokenAccountType = "education"
)

var (
	// VPPTokenAccountTypePBusiness is a pointer to VPPTokenAccountTypeVBusiness
	VPPTokenAccountTypePBusiness = &_VPPTokenAccountTypePBusiness
	// VPPTokenAccountTypePEducation is a pointer to VPPTokenAccountTypeVEducation
	VPPTokenAccountTypePEducation = &_VPPTokenAccountTypePEducation
)

var (
	_VPPTokenAccountTypePBusiness  = VPPTokenAccountTypeVBusiness
	_VPPTokenAccountTypePEducation = VPPTokenAccountTypeVEducation
)

// VPPTokenState undocumented
type VPPTokenState string

const (
	// VPPTokenStateVUnknown undocumented
	VPPTokenStateVUnknown VPPTokenState = "unknown"
	// VPPTokenStateVValid undocumented
	VPPTokenStateVValid VPPTokenState = "valid"
	// VPPTokenStateVExpired undocumented
	VPPTokenStateVExpired VPPTokenState = "expired"
	// VPPTokenStateVInvalid undocumented
	VPPTokenStateVInvalid VPPTokenState = "invalid"
	// VPPTokenStateVAssignedToExternalMDM undocumented
	VPPTokenStateVAssignedToExternalMDM VPPTokenState = "assignedToExternalMDM"
)

var (
	// VPPTokenStatePUnknown is a pointer to VPPTokenStateVUnknown
	VPPTokenStatePUnknown = &_VPPTokenStatePUnknown
	// VPPTokenStatePValid is a pointer to VPPTokenStateVValid
	VPPTokenStatePValid = &_VPPTokenStatePValid
	// VPPTokenStatePExpired is a pointer to VPPTokenStateVExpired
	VPPTokenStatePExpired = &_VPPTokenStatePExpired
	// VPPTokenStatePInvalid is a pointer to VPPTokenStateVInvalid
	VPPTokenStatePInvalid = &_VPPTokenStatePInvalid
	// VPPTokenStatePAssignedToExternalMDM is a pointer to VPPTokenStateVAssignedToExternalMDM
	VPPTokenStatePAssignedToExternalMDM = &_VPPTokenStatePAssignedToExternalMDM
)

var (
	_VPPTokenStatePUnknown               = VPPTokenStateVUnknown
	_VPPTokenStatePValid                 = VPPTokenStateVValid
	_VPPTokenStatePExpired               = VPPTokenStateVExpired
	_VPPTokenStatePInvalid               = VPPTokenStateVInvalid
	_VPPTokenStatePAssignedToExternalMDM = VPPTokenStateVAssignedToExternalMDM
)

// VPPTokenSyncStatus undocumented
type VPPTokenSyncStatus string

const (
	// VPPTokenSyncStatusVNone undocumented
	VPPTokenSyncStatusVNone VPPTokenSyncStatus = "none"
	// VPPTokenSyncStatusVInProgress undocumented
	VPPTokenSyncStatusVInProgress VPPTokenSyncStatus = "inProgress"
	// VPPTokenSyncStatusVCompleted undocumented
	VPPTokenSyncStatusVCompleted VPPTokenSyncStatus = "completed"
	// VPPTokenSyncStatusVFailed undocumented
	VPPTokenSyncStatusVFailed VPPTokenSyncStatus = "failed"
)

var (
	// VPPTokenSyncStatusPNone is a pointer to VPPTokenSyncStatusVNone
	VPPTokenSyncStatusPNone = &_VPPTokenSyncStatusPNone
	// VPPTokenSyncStatusPInProgress is a pointer to VPPTokenSyncStatusVInProgress
	VPPTokenSyncStatusPInProgress = &_VPPTokenSyncStatusPInProgress
	// VPPTokenSyncStatusPCompleted is a pointer to VPPTokenSyncStatusVCompleted
	VPPTokenSyncStatusPCompleted = &_VPPTokenSyncStatusPCompleted
	// VPPTokenSyncStatusPFailed is a pointer to VPPTokenSyncStatusVFailed
	VPPTokenSyncStatusPFailed = &_VPPTokenSyncStatusPFailed
)

var (
	_VPPTokenSyncStatusPNone       = VPPTokenSyncStatusVNone
	_VPPTokenSyncStatusPInProgress = VPPTokenSyncStatusVInProgress
	_VPPTokenSyncStatusPCompleted  = VPPTokenSyncStatusVCompleted
	_VPPTokenSyncStatusPFailed     = VPPTokenSyncStatusVFailed
)
