// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// FileHash undocumented
type FileHash struct {
	// HashType undocumented
	HashType *FileHashType `json:"hashType,omitempty"`
	// HashValue undocumented
	HashValue *string `json:"hashValue,omitempty"`
}
