// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// GroupSettingTemplate undocumented
type GroupSettingTemplate struct {
	// DirectoryObject is the base model of GroupSettingTemplate
	DirectoryObject
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// Values undocumented
	Values []SettingTemplateValue `json:"values,omitempty"`
}
