// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// InferenceClassification undocumented
type InferenceClassification struct {
	Entity
	// Overrides undocumented
	Overrides []InferenceClassificationOverride `json:"overrides,omitempty"`
}
