// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedAppPinCharacterSet undocumented
type ManagedAppPinCharacterSet string

const (
	// ManagedAppPinCharacterSetVNumeric undocumented
	ManagedAppPinCharacterSetVNumeric ManagedAppPinCharacterSet = "numeric"
	// ManagedAppPinCharacterSetVAlphanumericAndSymbol undocumented
	ManagedAppPinCharacterSetVAlphanumericAndSymbol ManagedAppPinCharacterSet = "alphanumericAndSymbol"
)

var (
	// ManagedAppPinCharacterSetPNumeric is a pointer to ManagedAppPinCharacterSetVNumeric
	ManagedAppPinCharacterSetPNumeric = &_ManagedAppPinCharacterSetPNumeric
	// ManagedAppPinCharacterSetPAlphanumericAndSymbol is a pointer to ManagedAppPinCharacterSetVAlphanumericAndSymbol
	ManagedAppPinCharacterSetPAlphanumericAndSymbol = &_ManagedAppPinCharacterSetPAlphanumericAndSymbol
)

var (
	_ManagedAppPinCharacterSetPNumeric               = ManagedAppPinCharacterSetVNumeric
	_ManagedAppPinCharacterSetPAlphanumericAndSymbol = ManagedAppPinCharacterSetVAlphanumericAndSymbol
)
