// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "time"

// OnenoteEntitySchemaObjectModel undocumented
type OnenoteEntitySchemaObjectModel struct {
	OnenoteEntityBaseModel
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
}
