// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// OpenTypeExtension undocumented
type OpenTypeExtension struct {
	Extension
	// ExtensionName undocumented
	ExtensionName *string `json:"extensionName,omitempty"`
}
