// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import (
	"context"
	"strings"
)

// EBookInstallSummaryRequestBuilder is request builder for EBookInstallSummary
type EBookInstallSummaryRequestBuilder struct{ BaseRequestBuilder }

// Request returns EBookInstallSummaryRequest
func (b *EBookInstallSummaryRequestBuilder) Request() *EBookInstallSummaryRequest {
	return &EBookInstallSummaryRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// EBookInstallSummaryRequest is request for EBookInstallSummary
type EBookInstallSummaryRequest struct{ BaseRequest }

// Get performs GET request for EBookInstallSummary
func (r *EBookInstallSummaryRequest) Get(ctx context.Context) (resObj *EBookInstallSummary, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for EBookInstallSummary
func (r *EBookInstallSummaryRequest) Update(ctx context.Context, reqObj *EBookInstallSummary) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for EBookInstallSummary
func (r *EBookInstallSummaryRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// BatchGet adds Get operation to Batch for EBookInstallSummary
func (r *EBookInstallSummaryRequest) BatchGet(batch *BatchRequest) error {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	var resObj EBookInstallSummary
	return batch.Add("GET", strings.TrimPrefix(r.baseURL+query, defaultBaseURL), nil, resObj)
}

// BatchUpdate adds Update operation to Batch for EBookInstallSummary
func (r *EBookInstallSummaryRequest) BatchUpdate(batch *BatchRequest, reqObj *EBookInstallSummary) error {
	return batch.Add("PATCH", strings.TrimPrefix(r.baseURL, defaultBaseURL), reqObj, nil)
}

// BatchDelete adds Delete operation to Batch for EBookInstallSummary
func (r *EBookInstallSummaryRequest) BatchDelete(batch *BatchRequest) error {
	return batch.Add("DELETE", strings.TrimPrefix(r.baseURL, defaultBaseURL), nil, nil)
}
