// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RoleAssignmentRequestBuilder is request builder for RoleAssignment
type RoleAssignmentRequestBuilder struct{ BaseRequestBuilder }

// Request returns RoleAssignmentRequest
func (b *RoleAssignmentRequestBuilder) Request() *RoleAssignmentRequest {
	return &RoleAssignmentRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// RoleAssignmentRequest is request for RoleAssignment
type RoleAssignmentRequest struct{ BaseRequest }

// Do performs HTTP request for RoleAssignment
func (r *RoleAssignmentRequest) Do(method, path string, reqObj interface{}) (resObj *RoleAssignment, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for RoleAssignment
func (r *RoleAssignmentRequest) Get() (*RoleAssignment, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for RoleAssignment
func (r *RoleAssignmentRequest) Update(reqObj *RoleAssignment) (*RoleAssignment, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for RoleAssignment
func (r *RoleAssignmentRequest) Delete() error {
	return r.JSONRequestWithPath("DELETE", "", nil, nil)
}

// RoleDefinition is navigation property
func (b *RoleAssignmentRequestBuilder) RoleDefinition() *RoleDefinitionRequestBuilder {
	bb := &RoleDefinitionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/roleDefinition"
	return bb
}
