// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SharedDriveItem undocumented
type SharedDriveItem struct {
	BaseItem
	// Owner undocumented
	Owner *IdentitySet `json:"owner,omitempty"`
	// DriveItem undocumented
	DriveItem *DriveItem `json:"driveItem,omitempty"`
	// Items undocumented
	Items []DriveItem `json:"items,omitempty"`
	// List undocumented
	List *List `json:"list,omitempty"`
	// ListItem undocumented
	ListItem *ListItem `json:"listItem,omitempty"`
	// Root undocumented
	Root *DriveItem `json:"root,omitempty"`
	// Site undocumented
	Site *Site `json:"site,omitempty"`
}
