// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ToneInfo undocumented
type ToneInfo struct {
	// SequenceID undocumented
	SequenceID *int `json:"sequenceId,omitempty"`
	// Tone undocumented
	Tone *Tone `json:"tone,omitempty"`
}
