// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// VppTokenSyncStatus undocumented
type VppTokenSyncStatus string

const (
	// VppTokenSyncStatusVNone undocumented
	VppTokenSyncStatusVNone VppTokenSyncStatus = "none"
	// VppTokenSyncStatusVInProgress undocumented
	VppTokenSyncStatusVInProgress VppTokenSyncStatus = "inProgress"
	// VppTokenSyncStatusVCompleted undocumented
	VppTokenSyncStatusVCompleted VppTokenSyncStatus = "completed"
	// VppTokenSyncStatusVFailed undocumented
	VppTokenSyncStatusVFailed VppTokenSyncStatus = "failed"
)

var (
	// VppTokenSyncStatusPNone is a pointer to VppTokenSyncStatusVNone
	VppTokenSyncStatusPNone = &_VppTokenSyncStatusPNone
	// VppTokenSyncStatusPInProgress is a pointer to VppTokenSyncStatusVInProgress
	VppTokenSyncStatusPInProgress = &_VppTokenSyncStatusPInProgress
	// VppTokenSyncStatusPCompleted is a pointer to VppTokenSyncStatusVCompleted
	VppTokenSyncStatusPCompleted = &_VppTokenSyncStatusPCompleted
	// VppTokenSyncStatusPFailed is a pointer to VppTokenSyncStatusVFailed
	VppTokenSyncStatusPFailed = &_VppTokenSyncStatusPFailed
)

var (
	_VppTokenSyncStatusPNone       = VppTokenSyncStatusVNone
	_VppTokenSyncStatusPInProgress = VppTokenSyncStatusVInProgress
	_VppTokenSyncStatusPCompleted  = VppTokenSyncStatusVCompleted
	_VppTokenSyncStatusPFailed     = VppTokenSyncStatusVFailed
)
