// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WorkbookChartLegendFormatRequestBuilder is request builder for WorkbookChartLegendFormat
type WorkbookChartLegendFormatRequestBuilder struct{ BaseRequestBuilder }

// Request returns WorkbookChartLegendFormatRequest
func (b *WorkbookChartLegendFormatRequestBuilder) Request() *WorkbookChartLegendFormatRequest {
	return &WorkbookChartLegendFormatRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// WorkbookChartLegendFormatRequest is request for WorkbookChartLegendFormat
type WorkbookChartLegendFormatRequest struct{ BaseRequest }

// Get performs GET request for WorkbookChartLegendFormat
func (r *WorkbookChartLegendFormatRequest) Get() (resObj *WorkbookChartLegendFormat, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest("GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for WorkbookChartLegendFormat
func (r *WorkbookChartLegendFormatRequest) Update(reqObj *WorkbookChartLegendFormat) error {
	return r.JSONRequest("PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for WorkbookChartLegendFormat
func (r *WorkbookChartLegendFormatRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}

// Fill is navigation property
func (b *WorkbookChartLegendFormatRequestBuilder) Fill() *WorkbookChartFillRequestBuilder {
	bb := &WorkbookChartFillRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/fill"
	return bb
}

// Font is navigation property
func (b *WorkbookChartLegendFormatRequestBuilder) Font() *WorkbookChartFontRequestBuilder {
	bb := &WorkbookChartFontRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/font"
	return bb
}
