// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WorkbookWorksheetProtectionProtectRequestParameter undocumented
type WorkbookWorksheetProtectionProtectRequestParameter struct {
	// Options undocumented
	Options *WorkbookWorksheetProtectionOptions `json:"options,omitempty"`
}

// WorkbookWorksheetProtectionUnprotectRequestParameter undocumented
type WorkbookWorksheetProtectionUnprotectRequestParameter struct {
}

//
type WorkbookWorksheetProtectionProtectRequestBuilder struct{ BaseRequestBuilder }

// Protect action undocumented
func (b *WorkbookWorksheetProtectionRequestBuilder) Protect(reqObj *WorkbookWorksheetProtectionProtectRequestParameter) *WorkbookWorksheetProtectionProtectRequestBuilder {
	bb := &WorkbookWorksheetProtectionProtectRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/protect"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type WorkbookWorksheetProtectionProtectRequest struct{ BaseRequest }

//
func (b *WorkbookWorksheetProtectionProtectRequestBuilder) Request() *WorkbookWorksheetProtectionProtectRequest {
	return &WorkbookWorksheetProtectionProtectRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

//
func (r *WorkbookWorksheetProtectionProtectRequest) Do(method, path string, reqObj interface{}) error {
	return r.JSONRequestWithPath(method, path, reqObj, nil)
}

//
func (r *WorkbookWorksheetProtectionProtectRequest) Post() error {
	return r.Do("POST", "", r.requestObject)
}

//
type WorkbookWorksheetProtectionUnprotectRequestBuilder struct{ BaseRequestBuilder }

// Unprotect action undocumented
func (b *WorkbookWorksheetProtectionRequestBuilder) Unprotect(reqObj *WorkbookWorksheetProtectionUnprotectRequestParameter) *WorkbookWorksheetProtectionUnprotectRequestBuilder {
	bb := &WorkbookWorksheetProtectionUnprotectRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/unprotect"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type WorkbookWorksheetProtectionUnprotectRequest struct{ BaseRequest }

//
func (b *WorkbookWorksheetProtectionUnprotectRequestBuilder) Request() *WorkbookWorksheetProtectionUnprotectRequest {
	return &WorkbookWorksheetProtectionUnprotectRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

//
func (r *WorkbookWorksheetProtectionUnprotectRequest) Do(method, path string, reqObj interface{}) error {
	return r.JSONRequestWithPath(method, path, reqObj, nil)
}

//
func (r *WorkbookWorksheetProtectionUnprotectRequest) Post() error {
	return r.Do("POST", "", r.requestObject)
}
