// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// AgedAccountsPayable undocumented
type AgedAccountsPayable struct {
	// Entity is the base model of AgedAccountsPayable
	Entity
	// VendorNumber undocumented
	VendorNumber *string `json:"vendorNumber,omitempty"`
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// CurrencyCode undocumented
	CurrencyCode *string `json:"currencyCode,omitempty"`
	// BalanceDue undocumented
	BalanceDue *int `json:"balanceDue,omitempty"`
	// CurrentAmount undocumented
	CurrentAmount *int `json:"currentAmount,omitempty"`
	// Period1Amount undocumented
	Period1Amount *int `json:"period1Amount,omitempty"`
	// Period2Amount undocumented
	Period2Amount *int `json:"period2Amount,omitempty"`
	// Period3Amount undocumented
	Period3Amount *int `json:"period3Amount,omitempty"`
	// AgedAsOfDate undocumented
	AgedAsOfDate *Date `json:"agedAsOfDate,omitempty"`
	// PeriodLengthFilter undocumented
	PeriodLengthFilter *string `json:"periodLengthFilter,omitempty"`
}

// AgedAccountsPayableRequestBuilder is request builder for AgedAccountsPayable
type AgedAccountsPayableRequestBuilder struct{ BaseRequestBuilder }

// Request returns AgedAccountsPayableRequest
func (b *AgedAccountsPayableRequestBuilder) Request() *AgedAccountsPayableRequest {
	return &AgedAccountsPayableRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// AgedAccountsPayableRequest is request for AgedAccountsPayable
type AgedAccountsPayableRequest struct{ BaseRequest }

// Get performs GET request for AgedAccountsPayable
func (r *AgedAccountsPayableRequest) Get(ctx context.Context) (resObj *AgedAccountsPayable, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for AgedAccountsPayable
func (r *AgedAccountsPayableRequest) Update(ctx context.Context, reqObj *AgedAccountsPayable) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for AgedAccountsPayable
func (r *AgedAccountsPayableRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
