// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidDeviceComplianceLocalActionLockDevice Local Action Lock Device Only Configuration
type AndroidDeviceComplianceLocalActionLockDevice struct {
	AndroidDeviceComplianceLocalActionBase
}
