// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AndroidVpnConnectionType undocumented
type AndroidVpnConnectionType string

const (
	// AndroidVpnConnectionTypeVCiscoAnyConnect undocumented
	AndroidVpnConnectionTypeVCiscoAnyConnect AndroidVpnConnectionType = "ciscoAnyConnect"
	// AndroidVpnConnectionTypeVPulseSecure undocumented
	AndroidVpnConnectionTypeVPulseSecure AndroidVpnConnectionType = "pulseSecure"
	// AndroidVpnConnectionTypeVF5EdgeClient undocumented
	AndroidVpnConnectionTypeVF5EdgeClient AndroidVpnConnectionType = "f5EdgeClient"
	// AndroidVpnConnectionTypeVDellSonicWallMobileConnect undocumented
	AndroidVpnConnectionTypeVDellSonicWallMobileConnect AndroidVpnConnectionType = "dellSonicWallMobileConnect"
	// AndroidVpnConnectionTypeVCheckPointCapsuleVpn undocumented
	AndroidVpnConnectionTypeVCheckPointCapsuleVpn AndroidVpnConnectionType = "checkPointCapsuleVpn"
	// AndroidVpnConnectionTypeVCitrix undocumented
	AndroidVpnConnectionTypeVCitrix AndroidVpnConnectionType = "citrix"
)

var (
	// AndroidVpnConnectionTypePCiscoAnyConnect is a pointer to AndroidVpnConnectionTypeVCiscoAnyConnect
	AndroidVpnConnectionTypePCiscoAnyConnect = &_AndroidVpnConnectionTypePCiscoAnyConnect
	// AndroidVpnConnectionTypePPulseSecure is a pointer to AndroidVpnConnectionTypeVPulseSecure
	AndroidVpnConnectionTypePPulseSecure = &_AndroidVpnConnectionTypePPulseSecure
	// AndroidVpnConnectionTypePF5EdgeClient is a pointer to AndroidVpnConnectionTypeVF5EdgeClient
	AndroidVpnConnectionTypePF5EdgeClient = &_AndroidVpnConnectionTypePF5EdgeClient
	// AndroidVpnConnectionTypePDellSonicWallMobileConnect is a pointer to AndroidVpnConnectionTypeVDellSonicWallMobileConnect
	AndroidVpnConnectionTypePDellSonicWallMobileConnect = &_AndroidVpnConnectionTypePDellSonicWallMobileConnect
	// AndroidVpnConnectionTypePCheckPointCapsuleVpn is a pointer to AndroidVpnConnectionTypeVCheckPointCapsuleVpn
	AndroidVpnConnectionTypePCheckPointCapsuleVpn = &_AndroidVpnConnectionTypePCheckPointCapsuleVpn
	// AndroidVpnConnectionTypePCitrix is a pointer to AndroidVpnConnectionTypeVCitrix
	AndroidVpnConnectionTypePCitrix = &_AndroidVpnConnectionTypePCitrix
)

var (
	_AndroidVpnConnectionTypePCiscoAnyConnect            = AndroidVpnConnectionTypeVCiscoAnyConnect
	_AndroidVpnConnectionTypePPulseSecure                = AndroidVpnConnectionTypeVPulseSecure
	_AndroidVpnConnectionTypePF5EdgeClient               = AndroidVpnConnectionTypeVF5EdgeClient
	_AndroidVpnConnectionTypePDellSonicWallMobileConnect = AndroidVpnConnectionTypeVDellSonicWallMobileConnect
	_AndroidVpnConnectionTypePCheckPointCapsuleVpn       = AndroidVpnConnectionTypeVCheckPointCapsuleVpn
	_AndroidVpnConnectionTypePCitrix                     = AndroidVpnConnectionTypeVCitrix
)
