// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// AttributeMappingSourceType undocumented
type AttributeMappingSourceType string

const (
	// AttributeMappingSourceTypeVAttribute undocumented
	AttributeMappingSourceTypeVAttribute AttributeMappingSourceType = "Attribute"
	// AttributeMappingSourceTypeVConstant undocumented
	AttributeMappingSourceTypeVConstant AttributeMappingSourceType = "Constant"
	// AttributeMappingSourceTypeVFunction undocumented
	AttributeMappingSourceTypeVFunction AttributeMappingSourceType = "Function"
)

var (
	// AttributeMappingSourceTypePAttribute is a pointer to AttributeMappingSourceTypeVAttribute
	AttributeMappingSourceTypePAttribute = &_AttributeMappingSourceTypePAttribute
	// AttributeMappingSourceTypePConstant is a pointer to AttributeMappingSourceTypeVConstant
	AttributeMappingSourceTypePConstant = &_AttributeMappingSourceTypePConstant
	// AttributeMappingSourceTypePFunction is a pointer to AttributeMappingSourceTypeVFunction
	AttributeMappingSourceTypePFunction = &_AttributeMappingSourceTypePFunction
)

var (
	_AttributeMappingSourceTypePAttribute = AttributeMappingSourceTypeVAttribute
	_AttributeMappingSourceTypePConstant  = AttributeMappingSourceTypeVConstant
	_AttributeMappingSourceTypePFunction  = AttributeMappingSourceTypeVFunction
)
