// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// BusinessFlowRequestBuilder is request builder for BusinessFlow
type BusinessFlowRequestBuilder struct{ BaseRequestBuilder }

// Request returns BusinessFlowRequest
func (b *BusinessFlowRequestBuilder) Request() *BusinessFlowRequest {
	return &BusinessFlowRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// BusinessFlowRequest is request for BusinessFlow
type BusinessFlowRequest struct{ BaseRequest }

// Get performs GET request for BusinessFlow
func (r *BusinessFlowRequest) Get() (resObj *BusinessFlow, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest("GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for BusinessFlow
func (r *BusinessFlowRequest) Update(reqObj *BusinessFlow) error {
	return r.JSONRequest("PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for BusinessFlow
func (r *BusinessFlowRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
