// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// BusinessFlowTemplateRequestBuilder is request builder for BusinessFlowTemplate
type BusinessFlowTemplateRequestBuilder struct{ BaseRequestBuilder }

// Request returns BusinessFlowTemplateRequest
func (b *BusinessFlowTemplateRequestBuilder) Request() *BusinessFlowTemplateRequest {
	return &BusinessFlowTemplateRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// BusinessFlowTemplateRequest is request for BusinessFlowTemplate
type BusinessFlowTemplateRequest struct{ BaseRequest }

// Do performs HTTP request for BusinessFlowTemplate
func (r *BusinessFlowTemplateRequest) Do(method, path string, reqObj interface{}) (resObj *BusinessFlowTemplate, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for BusinessFlowTemplate
func (r *BusinessFlowTemplateRequest) Get() (*BusinessFlowTemplate, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for BusinessFlowTemplate
func (r *BusinessFlowTemplateRequest) Update(reqObj *BusinessFlowTemplate) (*BusinessFlowTemplate, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for BusinessFlowTemplate
func (r *BusinessFlowTemplateRequest) Delete() error {
	return r.JSONRequestWithPath("DELETE", "", nil, nil)
}
