// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CalendarSharingAction undocumented
type CalendarSharingAction string

const (
	// CalendarSharingActionVAccept undocumented
	CalendarSharingActionVAccept CalendarSharingAction = "accept"
	// CalendarSharingActionVAcceptAndViewCalendar undocumented
	CalendarSharingActionVAcceptAndViewCalendar CalendarSharingAction = "acceptAndViewCalendar"
	// CalendarSharingActionVViewCalendar undocumented
	CalendarSharingActionVViewCalendar CalendarSharingAction = "viewCalendar"
	// CalendarSharingActionVAddThisCalendar undocumented
	CalendarSharingActionVAddThisCalendar CalendarSharingAction = "addThisCalendar"
)

var (
	// CalendarSharingActionPAccept is a pointer to CalendarSharingActionVAccept
	CalendarSharingActionPAccept = &_CalendarSharingActionPAccept
	// CalendarSharingActionPAcceptAndViewCalendar is a pointer to CalendarSharingActionVAcceptAndViewCalendar
	CalendarSharingActionPAcceptAndViewCalendar = &_CalendarSharingActionPAcceptAndViewCalendar
	// CalendarSharingActionPViewCalendar is a pointer to CalendarSharingActionVViewCalendar
	CalendarSharingActionPViewCalendar = &_CalendarSharingActionPViewCalendar
	// CalendarSharingActionPAddThisCalendar is a pointer to CalendarSharingActionVAddThisCalendar
	CalendarSharingActionPAddThisCalendar = &_CalendarSharingActionPAddThisCalendar
)

var (
	_CalendarSharingActionPAccept                = CalendarSharingActionVAccept
	_CalendarSharingActionPAcceptAndViewCalendar = CalendarSharingActionVAcceptAndViewCalendar
	_CalendarSharingActionPViewCalendar          = CalendarSharingActionVViewCalendar
	_CalendarSharingActionPAddThisCalendar       = CalendarSharingActionVAddThisCalendar
)
