// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// CalendarSharingActionImportance undocumented
type CalendarSharingActionImportance string

const (
	// CalendarSharingActionImportanceVPrimary undocumented
	CalendarSharingActionImportanceVPrimary CalendarSharingActionImportance = "primary"
	// CalendarSharingActionImportanceVSecondary undocumented
	CalendarSharingActionImportanceVSecondary CalendarSharingActionImportance = "secondary"
)

var (
	// CalendarSharingActionImportancePPrimary is a pointer to CalendarSharingActionImportanceVPrimary
	CalendarSharingActionImportancePPrimary = &_CalendarSharingActionImportancePPrimary
	// CalendarSharingActionImportancePSecondary is a pointer to CalendarSharingActionImportanceVSecondary
	CalendarSharingActionImportancePSecondary = &_CalendarSharingActionImportancePSecondary
)

var (
	_CalendarSharingActionImportancePPrimary   = CalendarSharingActionImportanceVPrimary
	_CalendarSharingActionImportancePSecondary = CalendarSharingActionImportanceVSecondary
)
