// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import (
	"context"
	"time"
)

// CartToClassAssociation CartToClassAssociation for associating device carts with classrooms.
type CartToClassAssociation struct {
	// Entity is the base model of CartToClassAssociation
	Entity
	// CreatedDateTime DateTime the object was created.
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// LastModifiedDateTime DateTime the object was last modified.
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// Version Version of the CartToClassAssociation.
	Version *int `json:"version,omitempty"`
	// DisplayName Admin provided name of the device configuration.
	DisplayName *string `json:"displayName,omitempty"`
	// Description Admin provided description of the CartToClassAssociation.
	Description *string `json:"description,omitempty"`
	// DeviceCartIDs Identifiers of device carts to be associated with classes.
	DeviceCartIDs []string `json:"deviceCartIds,omitempty"`
	// ClassroomIDs Identifiers of classrooms to be associated with device carts.
	ClassroomIDs []string `json:"classroomIds,omitempty"`
}

// CartToClassAssociationRequestBuilder is request builder for CartToClassAssociation
type CartToClassAssociationRequestBuilder struct{ BaseRequestBuilder }

// Request returns CartToClassAssociationRequest
func (b *CartToClassAssociationRequestBuilder) Request() *CartToClassAssociationRequest {
	return &CartToClassAssociationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// CartToClassAssociationRequest is request for CartToClassAssociation
type CartToClassAssociationRequest struct{ BaseRequest }

// Get performs GET request for CartToClassAssociation
func (r *CartToClassAssociationRequest) Get(ctx context.Context) (resObj *CartToClassAssociation, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for CartToClassAssociation
func (r *CartToClassAssociationRequest) Update(ctx context.Context, reqObj *CartToClassAssociation) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for CartToClassAssociation
func (r *CartToClassAssociationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
