// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// ChatThreadRequestBuilder is request builder for ChatThread
type ChatThreadRequestBuilder struct{ BaseRequestBuilder }

// Request returns ChatThreadRequest
func (b *ChatThreadRequestBuilder) Request() *ChatThreadRequest {
	return &ChatThreadRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ChatThreadRequest is request for ChatThread
type ChatThreadRequest struct{ BaseRequest }

// Get performs GET request for ChatThread
func (r *ChatThreadRequest) Get(ctx context.Context) (resObj *ChatThread, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ChatThread
func (r *ChatThreadRequest) Update(ctx context.Context, reqObj *ChatThread) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ChatThread
func (r *ChatThreadRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// RootMessage is navigation property
func (b *ChatThreadRequestBuilder) RootMessage() *ChatMessageRequestBuilder {
	bb := &ChatMessageRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/rootMessage"
	return bb
}
