// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ChatMessageType undocumented
type ChatMessageType string

const (
	// ChatMessageTypeVMessage undocumented
	ChatMessageTypeVMessage ChatMessageType = "message"
	// ChatMessageTypeVChatEvent undocumented
	ChatMessageTypeVChatEvent ChatMessageType = "chatEvent"
	// ChatMessageTypeVTyping undocumented
	ChatMessageTypeVTyping ChatMessageType = "typing"
)

var (
	// ChatMessageTypePMessage is a pointer to ChatMessageTypeVMessage
	ChatMessageTypePMessage = &_ChatMessageTypePMessage
	// ChatMessageTypePChatEvent is a pointer to ChatMessageTypeVChatEvent
	ChatMessageTypePChatEvent = &_ChatMessageTypePChatEvent
	// ChatMessageTypePTyping is a pointer to ChatMessageTypeVTyping
	ChatMessageTypePTyping = &_ChatMessageTypePTyping
)

var (
	_ChatMessageTypePMessage   = ChatMessageTypeVMessage
	_ChatMessageTypePChatEvent = ChatMessageTypeVChatEvent
	_ChatMessageTypePTyping    = ChatMessageTypeVTyping
)
