// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceAppManagementTaskPriority undocumented
type DeviceAppManagementTaskPriority string

const (
	// DeviceAppManagementTaskPriorityVNone undocumented
	DeviceAppManagementTaskPriorityVNone DeviceAppManagementTaskPriority = "none"
	// DeviceAppManagementTaskPriorityVHigh undocumented
	DeviceAppManagementTaskPriorityVHigh DeviceAppManagementTaskPriority = "high"
	// DeviceAppManagementTaskPriorityVLow undocumented
	DeviceAppManagementTaskPriorityVLow DeviceAppManagementTaskPriority = "low"
)

var (
	// DeviceAppManagementTaskPriorityPNone is a pointer to DeviceAppManagementTaskPriorityVNone
	DeviceAppManagementTaskPriorityPNone = &_DeviceAppManagementTaskPriorityPNone
	// DeviceAppManagementTaskPriorityPHigh is a pointer to DeviceAppManagementTaskPriorityVHigh
	DeviceAppManagementTaskPriorityPHigh = &_DeviceAppManagementTaskPriorityPHigh
	// DeviceAppManagementTaskPriorityPLow is a pointer to DeviceAppManagementTaskPriorityVLow
	DeviceAppManagementTaskPriorityPLow = &_DeviceAppManagementTaskPriorityPLow
)

var (
	_DeviceAppManagementTaskPriorityPNone = DeviceAppManagementTaskPriorityVNone
	_DeviceAppManagementTaskPriorityPHigh = DeviceAppManagementTaskPriorityVHigh
	_DeviceAppManagementTaskPriorityPLow  = DeviceAppManagementTaskPriorityVLow
)
