// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementTemplateCreateInstanceRequestParameter undocumented
type DeviceManagementTemplateCreateInstanceRequestParameter struct {
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// SettingsDelta undocumented
	SettingsDelta []DeviceManagementSettingInstance `json:"settingsDelta,omitempty"`
	// RoleScopeTagIDs undocumented
	RoleScopeTagIDs []string `json:"roleScopeTagIds,omitempty"`
}

//
type DeviceManagementTemplateCreateInstanceRequestBuilder struct{ BaseRequestBuilder }

// CreateInstance action undocumented
func (b *DeviceManagementTemplateRequestBuilder) CreateInstance(reqObj *DeviceManagementTemplateCreateInstanceRequestParameter) *DeviceManagementTemplateCreateInstanceRequestBuilder {
	bb := &DeviceManagementTemplateCreateInstanceRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/createInstance"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type DeviceManagementTemplateCreateInstanceRequest struct{ BaseRequest }

//
func (b *DeviceManagementTemplateCreateInstanceRequestBuilder) Request() *DeviceManagementTemplateCreateInstanceRequest {
	return &DeviceManagementTemplateCreateInstanceRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

//
func (r *DeviceManagementTemplateCreateInstanceRequest) Post() (resObj *DeviceManagementIntent, err error) {
	err = r.JSONRequest("POST", "", r.requestObject, &resObj)
	return
}
