// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementSettingXMLConstraint undocumented
type DeviceManagementSettingXMLConstraint struct {
	DeviceManagementConstraint
}
