// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementTemplateSettingCategory Entity representing a template setting category
type DeviceManagementTemplateSettingCategory struct {
	DeviceManagementSettingCategory
	// RecommendedSettings undocumented
	RecommendedSettings []DeviceManagementSettingInstance `json:"recommendedSettings,omitempty"`
}
