// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceManagementExchangeAccessRule undocumented
type DeviceManagementExchangeAccessRule struct {
	// DeviceClass Device Class which will be impacted by this rule.
	DeviceClass *DeviceManagementExchangeDeviceClass `json:"deviceClass,omitempty"`
	// AccessLevel Access Level for Exchange granted by this rule.
	AccessLevel *DeviceManagementExchangeAccessLevel `json:"accessLevel,omitempty"`
}
