// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// DeviceHealthScript Intune will provide customer the ability to run their Powershell scripts on the enrolled windows 10 Azure Active Directory joined devices. The script can be run once or periodically.
type DeviceHealthScript struct {
	DeviceManagementScript
	// ComplianceRule undocumented
	ComplianceRule *DeviceHealthScriptComplianceRule `json:"complianceRule,omitempty"`
	// RemediationScriptContent undocumented
	RemediationScriptContent *Binary `json:"remediationScriptContent,omitempty"`
}
