// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EducationSynchronizationConnectionSettings undocumented
type EducationSynchronizationConnectionSettings struct {
	// ClientID undocumented
	ClientID *string `json:"clientId,omitempty"`
	// ClientSecret undocumented
	ClientSecret *string `json:"clientSecret,omitempty"`
}
