// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// EducationOutcomeRequestBuilder is request builder for EducationOutcome
type EducationOutcomeRequestBuilder struct{ BaseRequestBuilder }

// Request returns EducationOutcomeRequest
func (b *EducationOutcomeRequestBuilder) Request() *EducationOutcomeRequest {
	return &EducationOutcomeRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// EducationOutcomeRequest is request for EducationOutcome
type EducationOutcomeRequest struct{ BaseRequest }

// Do performs HTTP request for EducationOutcome
func (r *EducationOutcomeRequest) Do(method, path string, reqObj interface{}) (resObj *EducationOutcome, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for EducationOutcome
func (r *EducationOutcomeRequest) Get() (*EducationOutcome, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for EducationOutcome
func (r *EducationOutcomeRequest) Update(reqObj *EducationOutcome) (*EducationOutcome, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for EducationOutcome
func (r *EducationOutcomeRequest) Delete() error {
	return r.JSONRequestWithPath("DELETE", "", nil, nil)
}
