// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "time"

// FeatureUsageDetail undocumented
type FeatureUsageDetail struct {
	// FeatureName undocumented
	FeatureName *string `json:"featureName,omitempty"`
	// LicenseRequired undocumented
	LicenseRequired *AzureADLicenseType `json:"licenseRequired,omitempty"`
	// LicenseAssigned undocumented
	LicenseAssigned *AzureADLicenseType `json:"licenseAssigned,omitempty"`
	// LastUsedDateTime undocumented
	LastUsedDateTime *time.Time `json:"lastUsedDateTime,omitempty"`
	// LastConfiguredDateTime undocumented
	LastConfiguredDateTime *time.Time `json:"lastConfiguredDateTime,omitempty"`
}
