// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ImplicitGrantSettings undocumented
type ImplicitGrantSettings struct {
	// EnableIDTokenIssuance undocumented
	EnableIDTokenIssuance *bool `json:"enableIdTokenIssuance,omitempty"`
	// EnableAccessTokenIssuance undocumented
	EnableAccessTokenIssuance *bool `json:"enableAccessTokenIssuance,omitempty"`
}
