// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ImportedWindowsAutopilotDeviceIdentityRequestBuilder is request builder for ImportedWindowsAutopilotDeviceIdentity
type ImportedWindowsAutopilotDeviceIdentityRequestBuilder struct{ BaseRequestBuilder }

// Request returns ImportedWindowsAutopilotDeviceIdentityRequest
func (b *ImportedWindowsAutopilotDeviceIdentityRequestBuilder) Request() *ImportedWindowsAutopilotDeviceIdentityRequest {
	return &ImportedWindowsAutopilotDeviceIdentityRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ImportedWindowsAutopilotDeviceIdentityRequest is request for ImportedWindowsAutopilotDeviceIdentity
type ImportedWindowsAutopilotDeviceIdentityRequest struct{ BaseRequest }

// Get performs GET request for ImportedWindowsAutopilotDeviceIdentity
func (r *ImportedWindowsAutopilotDeviceIdentityRequest) Get() (resObj *ImportedWindowsAutopilotDeviceIdentity, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest("GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ImportedWindowsAutopilotDeviceIdentity
func (r *ImportedWindowsAutopilotDeviceIdentityRequest) Update(reqObj *ImportedWindowsAutopilotDeviceIdentity) error {
	return r.JSONRequest("PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ImportedWindowsAutopilotDeviceIdentity
func (r *ImportedWindowsAutopilotDeviceIdentityRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
