// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// InsightValueInt undocumented
type InsightValueInt struct {
	UserExperienceAnalyticsInsightValue
	// Value undocumented
	Value *int `json:"value,omitempty"`
}
