// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// IOSEducationDeviceConfiguration iOS Education configuration profile
type IOSEducationDeviceConfiguration struct {
	DeviceConfiguration
}
