// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

// JournalRequestBuilder is request builder for Journal
type JournalRequestBuilder struct{ BaseRequestBuilder }

// Request returns JournalRequest
func (b *JournalRequestBuilder) Request() *JournalRequest {
	return &JournalRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// JournalRequest is request for Journal
type JournalRequest struct{ BaseRequest }

// Do performs HTTP request for Journal
func (r *JournalRequest) Do(method, path string, reqObj interface{}) (resObj *Journal, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for Journal
func (r *JournalRequest) Get() (*Journal, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for Journal
func (r *JournalRequest) Update(reqObj *Journal) (*Journal, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for Journal
func (r *JournalRequest) Delete() error {
	return r.JSONRequestWithPath("DELETE", "", nil, nil)
}

// Account is navigation property
func (b *JournalRequestBuilder) Account() *AccountRequestBuilder {
	bb := &AccountRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/account"
	return bb
}

// JournalLines returns request builder for JournalLine collection
func (b *JournalRequestBuilder) JournalLines() *JournalJournalLinesCollectionRequestBuilder {
	bb := &JournalJournalLinesCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/journalLines"
	return bb
}

// JournalJournalLinesCollectionRequestBuilder is request builder for JournalLine collection
type JournalJournalLinesCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for JournalLine collection
func (b *JournalJournalLinesCollectionRequestBuilder) Request() *JournalJournalLinesCollectionRequest {
	return &JournalJournalLinesCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for JournalLine item
func (b *JournalJournalLinesCollectionRequestBuilder) ID(id string) *JournalLineRequestBuilder {
	bb := &JournalLineRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// JournalJournalLinesCollectionRequest is request for JournalLine collection
type JournalJournalLinesCollectionRequest struct{ BaseRequest }

// Do performs HTTP request for JournalLine collection
func (r *JournalJournalLinesCollectionRequest) Do(method, path string, reqObj interface{}) (resObj *JournalLine, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Paging perfoms paging operation for JournalLine collection
func (r *JournalJournalLinesCollectionRequest) Paging(method, path string, obj interface{}) ([]JournalLine, error) {
	req, err := r.NewJSONRequestWithPath(method, path, obj)
	if err != nil {
		return nil, err
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []JournalLine
	for {
		defer res.Body.Close()
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			return nil, fmt.Errorf("%s: %s", res.Status, string(b))
		}
		var (
			paging Paging
			value  []JournalLine
		)
		err := json.NewDecoder(res.Body).Decode(&paging)
		if err != nil {
			return nil, err
		}
		err = json.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if len(paging.NextLink) == 0 {
			return values, nil
		}
		res, err = r.client.Get(paging.NextLink)
		if err != nil {
			return nil, err
		}
	}
}

// Get performs GET request for JournalLine collection
func (r *JournalJournalLinesCollectionRequest) Get() ([]JournalLine, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging("GET", query, nil)
}

// Add performs POST request for JournalLine collection
func (r *JournalJournalLinesCollectionRequest) Add(reqObj *JournalLine) (*JournalLine, error) {
	return r.Do("POST", "", reqObj)
}
