// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// MailboxUsageMailboxCounts undocumented
type MailboxUsageMailboxCounts struct {
	// Entity is the base model of MailboxUsageMailboxCounts
	Entity
	// ReportRefreshDate undocumented
	ReportRefreshDate *Date `json:"reportRefreshDate,omitempty"`
	// Total undocumented
	Total *int `json:"total,omitempty"`
	// Active undocumented
	Active *int `json:"active,omitempty"`
	// ReportDate undocumented
	ReportDate *Date `json:"reportDate,omitempty"`
	// ReportPeriod undocumented
	ReportPeriod *string `json:"reportPeriod,omitempty"`
}
