// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagementState undocumented
type ManagementState string

const (
	// ManagementStateVManaged undocumented
	ManagementStateVManaged ManagementState = "managed"
	// ManagementStateVRetirePending undocumented
	ManagementStateVRetirePending ManagementState = "retirePending"
	// ManagementStateVRetireFailed undocumented
	ManagementStateVRetireFailed ManagementState = "retireFailed"
	// ManagementStateVWipePending undocumented
	ManagementStateVWipePending ManagementState = "wipePending"
	// ManagementStateVWipeFailed undocumented
	ManagementStateVWipeFailed ManagementState = "wipeFailed"
	// ManagementStateVUnhealthy undocumented
	ManagementStateVUnhealthy ManagementState = "unhealthy"
	// ManagementStateVDeletePending undocumented
	ManagementStateVDeletePending ManagementState = "deletePending"
	// ManagementStateVRetireIssued undocumented
	ManagementStateVRetireIssued ManagementState = "retireIssued"
	// ManagementStateVWipeIssued undocumented
	ManagementStateVWipeIssued ManagementState = "wipeIssued"
	// ManagementStateVWipeCanceled undocumented
	ManagementStateVWipeCanceled ManagementState = "wipeCanceled"
	// ManagementStateVRetireCanceled undocumented
	ManagementStateVRetireCanceled ManagementState = "retireCanceled"
	// ManagementStateVDiscovered undocumented
	ManagementStateVDiscovered ManagementState = "discovered"
)

var (
	// ManagementStatePManaged is a pointer to ManagementStateVManaged
	ManagementStatePManaged = &_ManagementStatePManaged
	// ManagementStatePRetirePending is a pointer to ManagementStateVRetirePending
	ManagementStatePRetirePending = &_ManagementStatePRetirePending
	// ManagementStatePRetireFailed is a pointer to ManagementStateVRetireFailed
	ManagementStatePRetireFailed = &_ManagementStatePRetireFailed
	// ManagementStatePWipePending is a pointer to ManagementStateVWipePending
	ManagementStatePWipePending = &_ManagementStatePWipePending
	// ManagementStatePWipeFailed is a pointer to ManagementStateVWipeFailed
	ManagementStatePWipeFailed = &_ManagementStatePWipeFailed
	// ManagementStatePUnhealthy is a pointer to ManagementStateVUnhealthy
	ManagementStatePUnhealthy = &_ManagementStatePUnhealthy
	// ManagementStatePDeletePending is a pointer to ManagementStateVDeletePending
	ManagementStatePDeletePending = &_ManagementStatePDeletePending
	// ManagementStatePRetireIssued is a pointer to ManagementStateVRetireIssued
	ManagementStatePRetireIssued = &_ManagementStatePRetireIssued
	// ManagementStatePWipeIssued is a pointer to ManagementStateVWipeIssued
	ManagementStatePWipeIssued = &_ManagementStatePWipeIssued
	// ManagementStatePWipeCanceled is a pointer to ManagementStateVWipeCanceled
	ManagementStatePWipeCanceled = &_ManagementStatePWipeCanceled
	// ManagementStatePRetireCanceled is a pointer to ManagementStateVRetireCanceled
	ManagementStatePRetireCanceled = &_ManagementStatePRetireCanceled
	// ManagementStatePDiscovered is a pointer to ManagementStateVDiscovered
	ManagementStatePDiscovered = &_ManagementStatePDiscovered
)

var (
	_ManagementStatePManaged        = ManagementStateVManaged
	_ManagementStatePRetirePending  = ManagementStateVRetirePending
	_ManagementStatePRetireFailed   = ManagementStateVRetireFailed
	_ManagementStatePWipePending    = ManagementStateVWipePending
	_ManagementStatePWipeFailed     = ManagementStateVWipeFailed
	_ManagementStatePUnhealthy      = ManagementStateVUnhealthy
	_ManagementStatePDeletePending  = ManagementStateVDeletePending
	_ManagementStatePRetireIssued   = ManagementStateVRetireIssued
	_ManagementStatePWipeIssued     = ManagementStateVWipeIssued
	_ManagementStatePWipeCanceled   = ManagementStateVWipeCanceled
	_ManagementStatePRetireCanceled = ManagementStateVRetireCanceled
	_ManagementStatePDiscovered     = ManagementStateVDiscovered
)
