// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ManagedAppPolicyDeploymentSummaryRequestBuilder is request builder for ManagedAppPolicyDeploymentSummary
type ManagedAppPolicyDeploymentSummaryRequestBuilder struct{ BaseRequestBuilder }

// Request returns ManagedAppPolicyDeploymentSummaryRequest
func (b *ManagedAppPolicyDeploymentSummaryRequestBuilder) Request() *ManagedAppPolicyDeploymentSummaryRequest {
	return &ManagedAppPolicyDeploymentSummaryRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ManagedAppPolicyDeploymentSummaryRequest is request for ManagedAppPolicyDeploymentSummary
type ManagedAppPolicyDeploymentSummaryRequest struct{ BaseRequest }

// Get performs GET request for ManagedAppPolicyDeploymentSummary
func (r *ManagedAppPolicyDeploymentSummaryRequest) Get() (resObj *ManagedAppPolicyDeploymentSummary, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest("GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ManagedAppPolicyDeploymentSummary
func (r *ManagedAppPolicyDeploymentSummaryRequest) Update(reqObj *ManagedAppPolicyDeploymentSummary) error {
	return r.JSONRequest("PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ManagedAppPolicyDeploymentSummary
func (r *ManagedAppPolicyDeploymentSummaryRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
