// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

// MobileAppTroubleshootingEventRequestBuilder is request builder for MobileAppTroubleshootingEvent
type MobileAppTroubleshootingEventRequestBuilder struct{ BaseRequestBuilder }

// Request returns MobileAppTroubleshootingEventRequest
func (b *MobileAppTroubleshootingEventRequestBuilder) Request() *MobileAppTroubleshootingEventRequest {
	return &MobileAppTroubleshootingEventRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// MobileAppTroubleshootingEventRequest is request for MobileAppTroubleshootingEvent
type MobileAppTroubleshootingEventRequest struct{ BaseRequest }

// Do performs HTTP request for MobileAppTroubleshootingEvent
func (r *MobileAppTroubleshootingEventRequest) Do(method, path string, reqObj interface{}) (resObj *MobileAppTroubleshootingEvent, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for MobileAppTroubleshootingEvent
func (r *MobileAppTroubleshootingEventRequest) Get() (*MobileAppTroubleshootingEvent, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for MobileAppTroubleshootingEvent
func (r *MobileAppTroubleshootingEventRequest) Update(reqObj *MobileAppTroubleshootingEvent) (*MobileAppTroubleshootingEvent, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for MobileAppTroubleshootingEvent
func (r *MobileAppTroubleshootingEventRequest) Delete() error {
	return r.JSONRequestWithPath("DELETE", "", nil, nil)
}

// AppLogCollectionRequests returns request builder for AppLogCollectionRequestObject collection
func (b *MobileAppTroubleshootingEventRequestBuilder) AppLogCollectionRequests() *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequestBuilder {
	bb := &MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/appLogCollectionRequests"
	return bb
}

// MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequestBuilder is request builder for AppLogCollectionRequestObject collection
type MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for AppLogCollectionRequestObject collection
func (b *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequestBuilder) Request() *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest {
	return &MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for AppLogCollectionRequestObject item
func (b *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequestBuilder) ID(id string) *AppLogCollectionRequestObjectRequestBuilder {
	bb := &AppLogCollectionRequestObjectRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest is request for AppLogCollectionRequestObject collection
type MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest struct{ BaseRequest }

// Do performs HTTP request for AppLogCollectionRequestObject collection
func (r *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest) Do(method, path string, reqObj interface{}) (resObj *AppLogCollectionRequestObject, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Paging perfoms paging operation for AppLogCollectionRequestObject collection
func (r *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest) Paging(method, path string, obj interface{}) ([]AppLogCollectionRequestObject, error) {
	req, err := r.NewJSONRequestWithPath(method, path, obj)
	if err != nil {
		return nil, err
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []AppLogCollectionRequestObject
	for {
		defer res.Body.Close()
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			return nil, fmt.Errorf("%s: %s", res.Status, string(b))
		}
		var (
			paging Paging
			value  []AppLogCollectionRequestObject
		)
		err := json.NewDecoder(res.Body).Decode(&paging)
		if err != nil {
			return nil, err
		}
		err = json.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if len(paging.NextLink) == 0 {
			return values, nil
		}
		res, err = r.client.Get(paging.NextLink)
		if err != nil {
			return nil, err
		}
	}
}

// Get performs GET request for AppLogCollectionRequestObject collection
func (r *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest) Get() ([]AppLogCollectionRequestObject, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging("GET", query, nil)
}

// Add performs POST request for AppLogCollectionRequestObject collection
func (r *MobileAppTroubleshootingEventAppLogCollectionRequestsCollectionRequest) Add(reqObj *AppLogCollectionRequestObject) (*AppLogCollectionRequestObject, error) {
	return r.Do("POST", "", reqObj)
}
