// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// NdesConnectorState undocumented
type NdesConnectorState string

const (
	// NdesConnectorStateVNone undocumented
	NdesConnectorStateVNone NdesConnectorState = "none"
	// NdesConnectorStateVActive undocumented
	NdesConnectorStateVActive NdesConnectorState = "active"
	// NdesConnectorStateVInactive undocumented
	NdesConnectorStateVInactive NdesConnectorState = "inactive"
)

var (
	// NdesConnectorStatePNone is a pointer to NdesConnectorStateVNone
	NdesConnectorStatePNone = &_NdesConnectorStatePNone
	// NdesConnectorStatePActive is a pointer to NdesConnectorStateVActive
	NdesConnectorStatePActive = &_NdesConnectorStatePActive
	// NdesConnectorStatePInactive is a pointer to NdesConnectorStateVInactive
	NdesConnectorStatePInactive = &_NdesConnectorStatePInactive
)

var (
	_NdesConnectorStatePNone     = NdesConnectorStateVNone
	_NdesConnectorStatePActive   = NdesConnectorStateVActive
	_NdesConnectorStatePInactive = NdesConnectorStateVInactive
)
