// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// NotificationRequestBuilder is request builder for Notification
type NotificationRequestBuilder struct{ BaseRequestBuilder }

// Request returns NotificationRequest
func (b *NotificationRequestBuilder) Request() *NotificationRequest {
	return &NotificationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// NotificationRequest is request for Notification
type NotificationRequest struct{ BaseRequest }

// Do performs HTTP request for Notification
func (r *NotificationRequest) Do(method, path string, reqObj interface{}) (resObj *Notification, err error) {
	err = r.JSONRequest(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for Notification
func (r *NotificationRequest) Get() (*Notification, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for Notification
func (r *NotificationRequest) Update(reqObj *Notification) (*Notification, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for Notification
func (r *NotificationRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
