// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// OfficeSuiteInstallProgressDisplayLevel undocumented
type OfficeSuiteInstallProgressDisplayLevel string

const (
	// OfficeSuiteInstallProgressDisplayLevelVNone undocumented
	OfficeSuiteInstallProgressDisplayLevelVNone OfficeSuiteInstallProgressDisplayLevel = "none"
	// OfficeSuiteInstallProgressDisplayLevelVFull undocumented
	OfficeSuiteInstallProgressDisplayLevelVFull OfficeSuiteInstallProgressDisplayLevel = "full"
)

var (
	// OfficeSuiteInstallProgressDisplayLevelPNone is a pointer to OfficeSuiteInstallProgressDisplayLevelVNone
	OfficeSuiteInstallProgressDisplayLevelPNone = &_OfficeSuiteInstallProgressDisplayLevelPNone
	// OfficeSuiteInstallProgressDisplayLevelPFull is a pointer to OfficeSuiteInstallProgressDisplayLevelVFull
	OfficeSuiteInstallProgressDisplayLevelPFull = &_OfficeSuiteInstallProgressDisplayLevelPFull
)

var (
	_OfficeSuiteInstallProgressDisplayLevelPNone = OfficeSuiteInstallProgressDisplayLevelVNone
	_OfficeSuiteInstallProgressDisplayLevelPFull = OfficeSuiteInstallProgressDisplayLevelVFull
)
