// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// PersonName undocumented
type PersonName struct {
	// ItemFacet is the base model of PersonName
	ItemFacet
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// First undocumented
	First *string `json:"first,omitempty"`
	// Initials undocumented
	Initials *string `json:"initials,omitempty"`
	// Last undocumented
	Last *string `json:"last,omitempty"`
	// LanguageTag undocumented
	LanguageTag *string `json:"languageTag,omitempty"`
	// Maiden undocumented
	Maiden *string `json:"maiden,omitempty"`
	// Middle undocumented
	Middle *string `json:"middle,omitempty"`
	// Nickname undocumented
	Nickname *string `json:"nickname,omitempty"`
	// Suffix undocumented
	Suffix *string `json:"suffix,omitempty"`
	// Title undocumented
	Title *string `json:"title,omitempty"`
	// Pronunciation undocumented
	Pronunciation *YomiPersonName `json:"pronunciation,omitempty"`
}

// PersonNameRequestBuilder is request builder for PersonName
type PersonNameRequestBuilder struct{ BaseRequestBuilder }

// Request returns PersonNameRequest
func (b *PersonNameRequestBuilder) Request() *PersonNameRequest {
	return &PersonNameRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// PersonNameRequest is request for PersonName
type PersonNameRequest struct{ BaseRequest }

// Get performs GET request for PersonName
func (r *PersonNameRequest) Get(ctx context.Context) (resObj *PersonName, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for PersonName
func (r *PersonNameRequest) Update(ctx context.Context, reqObj *PersonName) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for PersonName
func (r *PersonNameRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
