// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// PrivilegedSignupStatus undocumented
type PrivilegedSignupStatus struct {
	Entity
	// IsRegistered undocumented
	IsRegistered *bool `json:"isRegistered,omitempty"`
	// Status undocumented
	Status *SetupStatus `json:"status,omitempty"`
}
