// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// ProgramResource undocumented
type ProgramResource struct {
	Identity
	// Type undocumented
	Type *string `json:"type,omitempty"`
}
