// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// PublicErrorDetail undocumented
type PublicErrorDetail struct {
	// Code undocumented
	Code *string `json:"code,omitempty"`
	// Message undocumented
	Message *string `json:"message,omitempty"`
	// Target undocumented
	Target *string `json:"target,omitempty"`
}
