// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RankedEmailAddress undocumented
type RankedEmailAddress struct {
	// Address undocumented
	Address *string `json:"address,omitempty"`
	// Rank undocumented
	Rank *float64 `json:"rank,omitempty"`
}
