// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingNewZealandTelevisionType undocumented
type RatingNewZealandTelevisionType string

const (
	// RatingNewZealandTelevisionTypeVAllAllowed undocumented
	RatingNewZealandTelevisionTypeVAllAllowed RatingNewZealandTelevisionType = "allAllowed"
	// RatingNewZealandTelevisionTypeVAllBlocked undocumented
	RatingNewZealandTelevisionTypeVAllBlocked RatingNewZealandTelevisionType = "allBlocked"
	// RatingNewZealandTelevisionTypeVGeneral undocumented
	RatingNewZealandTelevisionTypeVGeneral RatingNewZealandTelevisionType = "general"
	// RatingNewZealandTelevisionTypeVParentalGuidance undocumented
	RatingNewZealandTelevisionTypeVParentalGuidance RatingNewZealandTelevisionType = "parentalGuidance"
	// RatingNewZealandTelevisionTypeVAdults undocumented
	RatingNewZealandTelevisionTypeVAdults RatingNewZealandTelevisionType = "adults"
)

var (
	// RatingNewZealandTelevisionTypePAllAllowed is a pointer to RatingNewZealandTelevisionTypeVAllAllowed
	RatingNewZealandTelevisionTypePAllAllowed = &_RatingNewZealandTelevisionTypePAllAllowed
	// RatingNewZealandTelevisionTypePAllBlocked is a pointer to RatingNewZealandTelevisionTypeVAllBlocked
	RatingNewZealandTelevisionTypePAllBlocked = &_RatingNewZealandTelevisionTypePAllBlocked
	// RatingNewZealandTelevisionTypePGeneral is a pointer to RatingNewZealandTelevisionTypeVGeneral
	RatingNewZealandTelevisionTypePGeneral = &_RatingNewZealandTelevisionTypePGeneral
	// RatingNewZealandTelevisionTypePParentalGuidance is a pointer to RatingNewZealandTelevisionTypeVParentalGuidance
	RatingNewZealandTelevisionTypePParentalGuidance = &_RatingNewZealandTelevisionTypePParentalGuidance
	// RatingNewZealandTelevisionTypePAdults is a pointer to RatingNewZealandTelevisionTypeVAdults
	RatingNewZealandTelevisionTypePAdults = &_RatingNewZealandTelevisionTypePAdults
)

var (
	_RatingNewZealandTelevisionTypePAllAllowed       = RatingNewZealandTelevisionTypeVAllAllowed
	_RatingNewZealandTelevisionTypePAllBlocked       = RatingNewZealandTelevisionTypeVAllBlocked
	_RatingNewZealandTelevisionTypePGeneral          = RatingNewZealandTelevisionTypeVGeneral
	_RatingNewZealandTelevisionTypePParentalGuidance = RatingNewZealandTelevisionTypeVParentalGuidance
	_RatingNewZealandTelevisionTypePAdults           = RatingNewZealandTelevisionTypeVAdults
)
