// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RatingJapanTelevisionType undocumented
type RatingJapanTelevisionType string

const (
	// RatingJapanTelevisionTypeVAllAllowed undocumented
	RatingJapanTelevisionTypeVAllAllowed RatingJapanTelevisionType = "allAllowed"
	// RatingJapanTelevisionTypeVAllBlocked undocumented
	RatingJapanTelevisionTypeVAllBlocked RatingJapanTelevisionType = "allBlocked"
	// RatingJapanTelevisionTypeVExplicitAllowed undocumented
	RatingJapanTelevisionTypeVExplicitAllowed RatingJapanTelevisionType = "explicitAllowed"
)

var (
	// RatingJapanTelevisionTypePAllAllowed is a pointer to RatingJapanTelevisionTypeVAllAllowed
	RatingJapanTelevisionTypePAllAllowed = &_RatingJapanTelevisionTypePAllAllowed
	// RatingJapanTelevisionTypePAllBlocked is a pointer to RatingJapanTelevisionTypeVAllBlocked
	RatingJapanTelevisionTypePAllBlocked = &_RatingJapanTelevisionTypePAllBlocked
	// RatingJapanTelevisionTypePExplicitAllowed is a pointer to RatingJapanTelevisionTypeVExplicitAllowed
	RatingJapanTelevisionTypePExplicitAllowed = &_RatingJapanTelevisionTypePExplicitAllowed
)

var (
	_RatingJapanTelevisionTypePAllAllowed      = RatingJapanTelevisionTypeVAllAllowed
	_RatingJapanTelevisionTypePAllBlocked      = RatingJapanTelevisionTypeVAllBlocked
	_RatingJapanTelevisionTypePExplicitAllowed = RatingJapanTelevisionTypeVExplicitAllowed
)
