// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import (
	"context"
	"strings"
)

// EnterpriseCodeSigningCertificateRequestBuilder is request builder for EnterpriseCodeSigningCertificate
type EnterpriseCodeSigningCertificateRequestBuilder struct{ BaseRequestBuilder }

// Request returns EnterpriseCodeSigningCertificateRequest
func (b *EnterpriseCodeSigningCertificateRequestBuilder) Request() *EnterpriseCodeSigningCertificateRequest {
	return &EnterpriseCodeSigningCertificateRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// EnterpriseCodeSigningCertificateRequest is request for EnterpriseCodeSigningCertificate
type EnterpriseCodeSigningCertificateRequest struct{ BaseRequest }

// Get performs GET request for EnterpriseCodeSigningCertificate
func (r *EnterpriseCodeSigningCertificateRequest) Get(ctx context.Context) (resObj *EnterpriseCodeSigningCertificate, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for EnterpriseCodeSigningCertificate
func (r *EnterpriseCodeSigningCertificateRequest) Update(ctx context.Context, reqObj *EnterpriseCodeSigningCertificate) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for EnterpriseCodeSigningCertificate
func (r *EnterpriseCodeSigningCertificateRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// BatchGet adds Get operation to Batch for EnterpriseCodeSigningCertificate
func (r *EnterpriseCodeSigningCertificateRequest) BatchGet(batch *BatchRequest) error {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	var resObj EnterpriseCodeSigningCertificate
	return batch.Add("GET", strings.TrimPrefix(r.baseURL+query, defaultBaseURL), nil, resObj)
}

// BatchUpdate adds Update operation to Batch for EnterpriseCodeSigningCertificate
func (r *EnterpriseCodeSigningCertificateRequest) BatchUpdate(batch *BatchRequest, reqObj *EnterpriseCodeSigningCertificate) error {
	return batch.Add("PATCH", strings.TrimPrefix(r.baseURL, defaultBaseURL), reqObj, nil)
}

// BatchDelete adds Delete operation to Batch for EnterpriseCodeSigningCertificate
func (r *EnterpriseCodeSigningCertificateRequest) BatchDelete(batch *BatchRequest) error {
	return batch.Add("DELETE", strings.TrimPrefix(r.baseURL, defaultBaseURL), nil, nil)
}
