// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// RunAsAccountType undocumented
type RunAsAccountType string

const (
	// RunAsAccountTypeVSystem undocumented
	RunAsAccountTypeVSystem RunAsAccountType = "system"
	// RunAsAccountTypeVUser undocumented
	RunAsAccountTypeVUser RunAsAccountType = "user"
)

var (
	// RunAsAccountTypePSystem is a pointer to RunAsAccountTypeVSystem
	RunAsAccountTypePSystem = &_RunAsAccountTypePSystem
	// RunAsAccountTypePUser is a pointer to RunAsAccountTypeVUser
	RunAsAccountTypePUser = &_RunAsAccountTypePUser
)

var (
	_RunAsAccountTypePSystem = RunAsAccountTypeVSystem
	_RunAsAccountTypePUser   = RunAsAccountTypeVUser
)
