// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// SettingValue undocumented
type SettingValue struct {
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// Value undocumented
	Value *string `json:"value,omitempty"`
}
