// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Shift undocumented
type Shift struct {
	ChangeTrackedEntity
	// SharedShift undocumented
	SharedShift *ShiftItem `json:"sharedShift,omitempty"`
	// DraftShift undocumented
	DraftShift *ShiftItem `json:"draftShift,omitempty"`
	// UserID undocumented
	UserID *string `json:"userId,omitempty"`
	// SchedulingGroupID undocumented
	SchedulingGroupID *string `json:"schedulingGroupId,omitempty"`
}
