// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// TeamsAsyncOperationRequestBuilder is request builder for TeamsAsyncOperation
type TeamsAsyncOperationRequestBuilder struct{ BaseRequestBuilder }

// Request returns TeamsAsyncOperationRequest
func (b *TeamsAsyncOperationRequestBuilder) Request() *TeamsAsyncOperationRequest {
	return &TeamsAsyncOperationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// TeamsAsyncOperationRequest is request for TeamsAsyncOperation
type TeamsAsyncOperationRequest struct{ BaseRequest }

// Get performs GET request for TeamsAsyncOperation
func (r *TeamsAsyncOperationRequest) Get() (resObj *TeamsAsyncOperation, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest("GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for TeamsAsyncOperation
func (r *TeamsAsyncOperationRequest) Update(reqObj *TeamsAsyncOperation) error {
	return r.JSONRequest("PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for TeamsAsyncOperation
func (r *TeamsAsyncOperationRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
