// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// UserPfxIntendedPurpose undocumented
type UserPfxIntendedPurpose string

const (
	// UserPfxIntendedPurposeVUnassigned undocumented
	UserPfxIntendedPurposeVUnassigned UserPfxIntendedPurpose = "unassigned"
	// UserPfxIntendedPurposeVSmimeEncryption undocumented
	UserPfxIntendedPurposeVSmimeEncryption UserPfxIntendedPurpose = "smimeEncryption"
	// UserPfxIntendedPurposeVSmimeSigning undocumented
	UserPfxIntendedPurposeVSmimeSigning UserPfxIntendedPurpose = "smimeSigning"
	// UserPfxIntendedPurposeVVpn undocumented
	UserPfxIntendedPurposeVVpn UserPfxIntendedPurpose = "vpn"
	// UserPfxIntendedPurposeVWifi undocumented
	UserPfxIntendedPurposeVWifi UserPfxIntendedPurpose = "wifi"
)

var (
	// UserPfxIntendedPurposePUnassigned is a pointer to UserPfxIntendedPurposeVUnassigned
	UserPfxIntendedPurposePUnassigned = &_UserPfxIntendedPurposePUnassigned
	// UserPfxIntendedPurposePSmimeEncryption is a pointer to UserPfxIntendedPurposeVSmimeEncryption
	UserPfxIntendedPurposePSmimeEncryption = &_UserPfxIntendedPurposePSmimeEncryption
	// UserPfxIntendedPurposePSmimeSigning is a pointer to UserPfxIntendedPurposeVSmimeSigning
	UserPfxIntendedPurposePSmimeSigning = &_UserPfxIntendedPurposePSmimeSigning
	// UserPfxIntendedPurposePVpn is a pointer to UserPfxIntendedPurposeVVpn
	UserPfxIntendedPurposePVpn = &_UserPfxIntendedPurposePVpn
	// UserPfxIntendedPurposePWifi is a pointer to UserPfxIntendedPurposeVWifi
	UserPfxIntendedPurposePWifi = &_UserPfxIntendedPurposePWifi
)

var (
	_UserPfxIntendedPurposePUnassigned      = UserPfxIntendedPurposeVUnassigned
	_UserPfxIntendedPurposePSmimeEncryption = UserPfxIntendedPurposeVSmimeEncryption
	_UserPfxIntendedPurposePSmimeSigning    = UserPfxIntendedPurposeVSmimeSigning
	_UserPfxIntendedPurposePVpn             = UserPfxIntendedPurposeVVpn
	_UserPfxIntendedPurposePWifi            = UserPfxIntendedPurposeVWifi
)
