// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// VppTokenRequestBuilder is request builder for VppToken
type VppTokenRequestBuilder struct{ BaseRequestBuilder }

// Request returns VppTokenRequest
func (b *VppTokenRequestBuilder) Request() *VppTokenRequest {
	return &VppTokenRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// VppTokenRequest is request for VppToken
type VppTokenRequest struct{ BaseRequest }

// Do performs HTTP request for VppToken
func (r *VppTokenRequest) Do(method, path string, reqObj interface{}) (resObj *VppToken, err error) {
	err = r.JSONRequest(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for VppToken
func (r *VppTokenRequest) Get() (*VppToken, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for VppToken
func (r *VppTokenRequest) Update(reqObj *VppToken) (*VppToken, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for VppToken
func (r *VppTokenRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
