// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// Win32LobAppNotification undocumented
type Win32LobAppNotification string

const (
	// Win32LobAppNotificationVShowAll undocumented
	Win32LobAppNotificationVShowAll Win32LobAppNotification = "showAll"
	// Win32LobAppNotificationVShowReboot undocumented
	Win32LobAppNotificationVShowReboot Win32LobAppNotification = "showReboot"
	// Win32LobAppNotificationVHideAll undocumented
	Win32LobAppNotificationVHideAll Win32LobAppNotification = "hideAll"
)

var (
	// Win32LobAppNotificationPShowAll is a pointer to Win32LobAppNotificationVShowAll
	Win32LobAppNotificationPShowAll = &_Win32LobAppNotificationPShowAll
	// Win32LobAppNotificationPShowReboot is a pointer to Win32LobAppNotificationVShowReboot
	Win32LobAppNotificationPShowReboot = &_Win32LobAppNotificationPShowReboot
	// Win32LobAppNotificationPHideAll is a pointer to Win32LobAppNotificationVHideAll
	Win32LobAppNotificationPHideAll = &_Win32LobAppNotificationPHideAll
)

var (
	_Win32LobAppNotificationPShowAll    = Win32LobAppNotificationVShowAll
	_Win32LobAppNotificationPShowReboot = Win32LobAppNotificationVShowReboot
	_Win32LobAppNotificationPHideAll    = Win32LobAppNotificationVHideAll
)
