// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

import "context"

// WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary Contains properties for the deployment summary of a WindowsDefenderApplicationControl supplemental policy.
type WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary struct {
	// Entity is the base model of WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary
	Entity
	// DeployedDeviceCount Number of Devices that have successfully deployed this WindowsDefenderApplicationControl supplemental policy.
	DeployedDeviceCount *int `json:"deployedDeviceCount,omitempty"`
	// FailedDeviceCount Number of Devices that have failed to deploy this WindowsDefenderApplicationControl supplemental policy.
	FailedDeviceCount *int `json:"failedDeviceCount,omitempty"`
}

// WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequestBuilder is request builder for WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary
type WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequestBuilder struct{ BaseRequestBuilder }

// Request returns WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest
func (b *WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequestBuilder) Request() *WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest {
	return &WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest is request for WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary
type WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest struct{ BaseRequest }

// Get performs GET request for WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary
func (r *WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest) Get(ctx context.Context) (resObj *WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary
func (r *WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest) Update(ctx context.Context, reqObj *WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummary
func (r *WindowsDefenderApplicationControlSupplementalPolicyDeploymentSummaryRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
