// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WindowsCertificateProfileBaseRequestBuilder is request builder for WindowsCertificateProfileBase
type WindowsCertificateProfileBaseRequestBuilder struct{ BaseRequestBuilder }

// Request returns WindowsCertificateProfileBaseRequest
func (b *WindowsCertificateProfileBaseRequestBuilder) Request() *WindowsCertificateProfileBaseRequest {
	return &WindowsCertificateProfileBaseRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// WindowsCertificateProfileBaseRequest is request for WindowsCertificateProfileBase
type WindowsCertificateProfileBaseRequest struct{ BaseRequest }

// Do performs HTTP request for WindowsCertificateProfileBase
func (r *WindowsCertificateProfileBaseRequest) Do(method, path string, reqObj interface{}) (resObj *WindowsCertificateProfileBase, err error) {
	err = r.JSONRequest(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for WindowsCertificateProfileBase
func (r *WindowsCertificateProfileBaseRequest) Get() (*WindowsCertificateProfileBase, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for WindowsCertificateProfileBase
func (r *WindowsCertificateProfileBaseRequest) Update(reqObj *WindowsCertificateProfileBase) (*WindowsCertificateProfileBase, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for WindowsCertificateProfileBase
func (r *WindowsCertificateProfileBaseRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}
