// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WorkbookChartSeriesFormatRequestBuilder is request builder for WorkbookChartSeriesFormat
type WorkbookChartSeriesFormatRequestBuilder struct{ BaseRequestBuilder }

// Request returns WorkbookChartSeriesFormatRequest
func (b *WorkbookChartSeriesFormatRequestBuilder) Request() *WorkbookChartSeriesFormatRequest {
	return &WorkbookChartSeriesFormatRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// WorkbookChartSeriesFormatRequest is request for WorkbookChartSeriesFormat
type WorkbookChartSeriesFormatRequest struct{ BaseRequest }

// Get performs GET request for WorkbookChartSeriesFormat
func (r *WorkbookChartSeriesFormatRequest) Get() (resObj *WorkbookChartSeriesFormat, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest("GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for WorkbookChartSeriesFormat
func (r *WorkbookChartSeriesFormatRequest) Update(reqObj *WorkbookChartSeriesFormat) error {
	return r.JSONRequest("PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for WorkbookChartSeriesFormat
func (r *WorkbookChartSeriesFormatRequest) Delete() error {
	return r.JSONRequest("DELETE", "", nil, nil)
}

// Fill is navigation property
func (b *WorkbookChartSeriesFormatRequestBuilder) Fill() *WorkbookChartFillRequestBuilder {
	bb := &WorkbookChartFillRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/fill"
	return bb
}

// Line is navigation property
func (b *WorkbookChartSeriesFormatRequestBuilder) Line() *WorkbookChartLineFormatRequestBuilder {
	bb := &WorkbookChartLineFormatRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/line"
	return bb
}
