// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WorkbookChartFontRequestBuilder is request builder for WorkbookChartFont
type WorkbookChartFontRequestBuilder struct{ BaseRequestBuilder }

// Request returns WorkbookChartFontRequest
func (b *WorkbookChartFontRequestBuilder) Request() *WorkbookChartFontRequest {
	return &WorkbookChartFontRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// WorkbookChartFontRequest is request for WorkbookChartFont
type WorkbookChartFontRequest struct{ BaseRequest }

// Do performs HTTP request for WorkbookChartFont
func (r *WorkbookChartFontRequest) Do(method, path string, reqObj interface{}) (resObj *WorkbookChartFont, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for WorkbookChartFont
func (r *WorkbookChartFontRequest) Get() (*WorkbookChartFont, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for WorkbookChartFont
func (r *WorkbookChartFontRequest) Update(reqObj *WorkbookChartFont) (*WorkbookChartFont, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for WorkbookChartFont
func (r *WorkbookChartFontRequest) Delete() error {
	return r.JSONRequestWithPath("DELETE", "", nil, nil)
}
