// Code generated by msgraph-generate.go DO NOT EDIT.

package msgraph

// WorkbookChartPointFormatRequestBuilder is request builder for WorkbookChartPointFormat
type WorkbookChartPointFormatRequestBuilder struct{ BaseRequestBuilder }

// Request returns WorkbookChartPointFormatRequest
func (b *WorkbookChartPointFormatRequestBuilder) Request() *WorkbookChartPointFormatRequest {
	return &WorkbookChartPointFormatRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// WorkbookChartPointFormatRequest is request for WorkbookChartPointFormat
type WorkbookChartPointFormatRequest struct{ BaseRequest }

// Do performs HTTP request for WorkbookChartPointFormat
func (r *WorkbookChartPointFormatRequest) Do(method, path string, reqObj interface{}) (resObj *WorkbookChartPointFormat, err error) {
	err = r.JSONRequestWithPath(method, path, reqObj, &resObj)
	return
}

// Get performs GET request for WorkbookChartPointFormat
func (r *WorkbookChartPointFormatRequest) Get() (*WorkbookChartPointFormat, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Do("GET", query, nil)
}

// Update performs PATCH request for WorkbookChartPointFormat
func (r *WorkbookChartPointFormatRequest) Update(reqObj *WorkbookChartPointFormat) (*WorkbookChartPointFormat, error) {
	return r.Do("PATCH", "", reqObj)
}

// Delete performs DELETE request for WorkbookChartPointFormat
func (r *WorkbookChartPointFormatRequest) Delete() error {
	return r.JSONRequestWithPath("DELETE", "", nil, nil)
}

// Fill is navigation property
func (b *WorkbookChartPointFormatRequestBuilder) Fill() *WorkbookChartFillRequestBuilder {
	bb := &WorkbookChartFillRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/fill"
	return bb
}
